### ISSUE TITLE
argument --timeout: conflicting option string: --timeout

### ISSUE THREAD

**Issue by nmoseman** [fitbeard/action-trigger-awx#16]
Getting a error while trying to use the action. 
from the output of the job: 

> awx job_templates launch 'test' -f human --monitor --timeout 3600       
> argument --timeout: conflicting option string: --timeout

Using AWX 21.12.0

Possibly related to this issue? https://github.com/ansible/awx/issues/13086

Second or third comment in the thread mentions there was a API change that might be related to the issue.  

Same command on awx command line 21.12.0 works fine (installed via pip).

**Comment by fitbeard** [comment]
@nmoseman thank you for report. Could you please test newest release and let me know if the error is gone?
